image: harbor.duowan.com/front_end/node:12.7.0

cache:
  key: ${CI_JOB_NAME}

before_script:
  - yarn config set registry https://npm-registry.duowan.com

stages:
  - build
  - release

# 构建
build:
  stage: build
  tags:
    - yyci_office
  only:
    - master
    - test
  artifacts:
    expire_in: 1 week
    paths:
    - dist
    - package.json
  script:
    - yarn install
    - npm run build

.release:
  stage: release
  tags:
    - yyci_office
  script:
    - yarn global add @yy/rv-cli
    - rv .

# 发布 - 测试环境
release_test:
  extends: .release
  only:
    - test

# 发布 - 生产环境
release_prod:
  extends: .release
  when: manual
  only:
    - master
