image: harbor.duowan.com/ued/kda

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - yarn config set registry https://npm-registry.duowan.com

stages:
  - build
  - release

# 构建
build:
  stage: build
  tags:
    - yyci_office
  only:
    - master
    - test
  artifacts:
    expire_in: 1 week
    paths:
    - dist
    - package.json
  script:
    - cp -r /data/kda-deps/node_modules/ ./node_modules/
    - yarn install
    - yarn build:swc

.release:
  stage: release
  tags:
    - yyci_office
  script:
    - yarn global add @yy/rv-cli
    - export RV_TOKEN=$RV_TOKEN
    - rv .

# 发布 - 测试环境
release_test:
  extends: .release
  only:
    - test

# 发布 - 生产环境
release_prod:
  extends: .release
  when: manual
  only:
    - master
