image: harbor.duowan.com/ued/kda

before_script:
  - yarn config set registry https://npm-registry.duowan.com

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - release

# 构建
build:
  stage: build
  tags:
    - yyci_office
  only:
    - master
    - test
  artifacts:
    expire_in: 1 week
    paths:
    - dist
    - package.json
  script:
    - kda-cache
    - yarn install
    - yarn build:release

.release:
  stage: release
  tags:
    - yyci_office
  script:
    - yarn global add @yy/rv-cli
    - rv .

# 发布 - 测试环境
release_test:
  extends: .release
  only:
    - test

# 发布 - 生产环境
release_production:
  extends: .release
  when: manual
  only:
    - master
